"""
Constants and configuration for the dashboard.
"""
# ============================================================================
# LANGUAGE CONFIGURATION
# ============================================================================

LANGUAGES = {
    'indonesia': {
        'dashboard_title': "Dashboard Analisis Kinerja Penjualan",
        'dashboard_controls': "Kontrol Dashboard",
        'upload_data': "Unggah Data",
        'upload_help': "Unggah file dengan kolom: Area, SubArea, Nama, Grade, Target, Sales",
        'file_loaded': "File berhasil diupload",
        'data_records': "Data",
        'period_detected': "Periode terdeteksi",
        'period_config': "Konfigurasi Periode Data",
        'month_start': "Bulan Mulai",
        'month_end': "Bulan Akhir",
        'year': "Tahun",
        'update_period': "Update Periode dari Pilihan",
        'period_updated': "Periode diupdate",
        'period_display': "Periode Data",
        'data_filters': "Filter Data",
        'select_area': "Pilih Area",
        'select_grade': "Pilih Grade",
        'performance_range': "Rentang Kinerja",
        'min_achievement': "Pencapaian Minimum (%)",
        'max_achievement': "Pencapaian Maksimum (%)",
        'performance_category': "Kategori Kinerja",
        'filter_summary': "Ringkasan Filter",
        'download_template': "Download Template",
        'download_help': "Download template untuk mengisi data sales",
        'period_label': "Period",
        'enhanced_dashboard': "Enhanced Analytics Dashboard",
        'kpis': "Indikator Kinerja Utama",
        'overall_achievement': "Pencapaian Keseluruhan",
        'average_performance': "Rata-rata Kinerja",
        'top_performer': "Top Performer",
        'team_size': "Ukuran Tim",
        'needs_attention': "Perlu Perhatian",
        'overview': "Overview",
        'performers': "Performers",
        'detailed_data': "Detailed Data",
        'recommendations': "Recommendations",
        'footer_text': "Dashboard updated automatically • Data period",
        'last_updated': "Last updated",
        'search_name': "Cari berdasarkan Nama",
        'sort_by': "Urutkan berdasarkan",
        'export_format': "Format Export",
        'records_shown': "Records Shown",
        'avg_achievement': "Avg Achievement",
        'total_gap': "Total Gap",
        'group_achievement': "Group Achievement",
        'excellent_performers': "Excellent Performers",
        'good_performers': "Good Performers",
        'average_performers': "Average Performers",
        'needs_improvement': "Needs Improvement",
        'top_performers': "Top 10 Performers",
        'bottom_performers': "Bottom 10 Performers",
        'executive_summary': "Executive Summary",
        'overall_status': "Overall Status",
        'risk_level': "Risk Level",
        'quick_wins': "Quick Wins",
        'benchmarks': "Benchmarks",
        'immediate_actions': "Immediate Priority Actions",
        'area_maps': "Peta Area",
        'geographic_distribution': "Distribusi Geografis",
        'map_type': "Pilih Jenis Peta",
        'interactive_map': "Peta Interaktif",
        'heatmap': "Heatmap",
        'bubble_map': "Bubble Map",
        'map_legend': "Legenda Peta",
        'performance_color': "Kode Warna Performa",
        'bubble_size': "Ukuran Bubble",
        'map_tips': "Tips Peta",
        'area_summary': "Ringkasan Area",
        'regional_analysis': "Analisis Regional",
        'top_performing_areas': "Area Berkinerja Terbaik",
        'areas_need_attention': "Area Perlu Perhatian"
    },
    'english': {
        'dashboard_title': "Sales Performance Analytics Dashboard",
        'dashboard_controls': "Dashboard Controls",
        'upload_data': "Upload Data File",
        'upload_help': "Upload file with columns: Area, SubArea, Nama, Grade, Target, Sales",
        'file_loaded': "File successfully uploaded",
        'data_records': "Data",
        'period_detected': "Period detected",
        'period_config': "Data Period Configuration",
        'month_start': "Start Month",
        'month_end': "End Month",
        'year': "Year",
        'update_period': "Update Period from Selection",
        'period_updated': "Period updated",
        'period_display': "Data Period",
        'data_filters': "Data Filters",
        'select_area': "Select Area",
        'select_grade': "Select Grade",
        'performance_range': "Performance Range",
        'min_achievement': "Minimum Achievement (%)",
        'max_achievement': "Maximum Achievement (%)",
        'performance_category': "Performance Category",
        'filter_summary': "Filter Summary",
        'download_template': "Download Template",
        'download_help': "Download template for sales data",
        'period_label': "Period",
        'enhanced_dashboard': "Enhanced Analytics Dashboard",
        'kpis': "Key Performance Indicators",
        'overall_achievement': "Overall Achievement",
        'average_performance': "Average Performance",
        'top_performer': "Top Performer",
        'team_size': "Team Size",
        'needs_attention': "Needs Attention",
        'overview': "Overview",
        'performers': "Performers",
        'detailed_data': "Detailed Data",
        'recommendations': "Recommendations",
        'footer_text': "Dashboard updated automatically • Data period",
        'last_updated': "Last updated",
        'search_name': "Search by Name",
        'sort_by': "Sort by",
        'export_format': "Export Format",
        'records_shown': "Records Shown",
        'avg_achievement': "Avg Achievement",
        'total_gap': "Total Gap",
        'group_achievement': "Group Achievement",
        'excellent_performers': "Excellent Performers",
        'good_performers': "Good Performers",
        'average_performers': "Average Performers",
        'needs_improvement': "Needs Improvement",
        'top_performers': "Top 10 Performers",
        'bottom_performers': "Bottom 10 Performers",
        'executive_summary': "Executive Summary",
        'overall_status': "Overall Status",
        'risk_level': "Risk Level",
        'quick_wins': "Quick Wins",
        'benchmarks': "Benchmarks",
        'immediate_actions': "Immediate Priority Actions",
        'area_maps': "Area Maps",
        'geographic_distribution': "Geographic Distribution",
        'map_type': "Select Map Type",
        'interactive_map': "Interactive Map",
        'heatmap': "Heatmap",
        'bubble_map': "Bubble Map",
        'map_legend': "Map Legend",
        'performance_color': "Performance Color Code",
        'bubble_size': "Bubble Size",
        'map_tips': "Map Tips",
        'area_summary': "Area Summary",
        'regional_analysis': "Regional Analysis",
        'top_performing_areas': "Top Performing Areas",
        'areas_need_attention': "Areas Need Attention"
    }
}

# Performance thresholds
PERFORMANCE_THRESHOLDS = {
    'EXCELLENT': 120,
    'GOOD': 100,
    'AVERAGE': 80,
    'BELOW_AVERAGE': 60,
    'POOR': 0
}

PERFORMANCE_CATEGORIES = ['Excellent', 'Good', 'Average', 'Below Average', 'Poor']

# Month mapping for Indonesian
BULAN_MAP = {
    'jan': 'Januari', 'feb': 'Februari', 'mar': 'Maret', 'apr': 'April',
    'mei': 'Mei', 'jun': 'Juni', 'jul': 'Juli', 'agu': 'Agustus',
    'sep': 'September', 'okt': 'Oktober', 'nov': 'November', 'des': 'Desember',
    'januari': 'Januari', 'februari': 'Februari', 'maret': 'Maret',
    'april': 'April', 'juni': 'Juni', 'juli': 'Juli',
    'agustus': 'Agustus', 'september': 'September',
    'oktober': 'Oktober', 'november': 'November', 'desember': 'Desember'
}

# Area coordinates
INDONESIA_COORDINATES = {
    'JAWA': {
        'Jakarta': {'lat': -6.2088, 'lon': 106.8456},
        'Bandung': {'lat': -6.9175, 'lon': 107.6191},
        'Surabaya': {'lat': -7.2575, 'lon': 112.7521},
        # ... all Jawa coordinates
    },
    # ... other islands
}